name: Build and Release Extension Catalog Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-chart:
    uses: jordojordo/ui-chart-workflow/.github/workflows/build-extension-container.yml@main
    permissions:
      actions: write
      contents: write
      deployments: write
      id-token: write
      packages: write
      pages: write
      pull-requests: write
    with:
      registry_target: ghcr.io
      registry_user: ${{ github.actor }}
    secrets: 
      registry_token: ${{ secrets.GITHUB_TOKEN }}
