name: Build and Release Extension Chart Repository

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  build-extension-chart:
    uses: jordojordo/ui-chart-workflow/.github/workflows/build-extension-chart.yml@main
    permissions:
      actions: write
      contents: write
      deployments: write
      id-token: write
      packages: write
      pages: write
      pull-requests: write
    with:
      TARGET_BRANCH: gh-pages
